### ISSUE TITLE
require vs import

### ISSUE THREAD

**Issue by VadimCpp** [SergBlack/mern-blog#5]
Все импорты в проекте с помощью ```require```, пример:
```
const config = require('config');
```

Почему не ```import```, пример:
```
import config from 'config';
```
?

**Comment by SergBlack** [comment]
Как я понимаю, при импорте модулей в nodejs надо использовать require(). Почитал это обсуждение https://stackoverflow.com/questions/31354559/using-node-js-require-vs-es6-import-export

**Comment by VadimCpp** [comment]
> Как я понимаю, при импорте модулей в nodejs надо использовать require(). Почитал это обсуждение https://stackoverflow.com/questions/31354559/using-node-js-require-vs-es6-import-export

Спасибо за ссылку, ознакомился.
