### ISSUE TITLE
yarn vs npm

### ISSUE THREAD

**Issue by VadimCpp** [SergBlack/mern-blog#6]
Почему в репозитории оба файла yarn.lock и package-lock.json ?
Что лучше: yarn или npm ?

**Comment by VadimCpp** [comment]
Ответ на первый вопрос:

> Whether you choose to commit yarn.lock or package-lock.json or both depends on whether those developing on your project are only using Yarn or NPM 5 or both. If your project is open-source, the most community-friendly thing to do would probably be to commit both and have an automated process to ensure yarn.lock and package-lock.json always stay in sync.

>Update: Yarn have now introduced an import command which will generate a yarn.lock file from a package-lock.json file. This could be useful for keeping the two files in sync.

Ref: https://stackoverflow.com/a/44904494/1775459

**Comment by SergBlack** [comment]
Спасибо за ссылку! Ознакомился и осознал )) Не имею каких-то конкретных предпочтений, но в последнее время почему-то запускаю yarn )
